### ISSUE TITLE
不成功啊

### ISSUE THREAD

**Issue by COOL1000** [web1n/feed-iwifi#1]
刷好固件，输入了，没有拨号成功，大佬，这是咋回事

**Comment by web1n** [comment]
从lede源码编译的吗

**Comment by COOL1000** [comment]
是的，按照你的方法编译进去的，转换协议输入账号保存应用后，等待连接没有网，会自动跳校园网认证界面，在认证界面认证成功后，多个设备连接能用，但是认证设备（电脑）断开连接后，几分钟就没网了。
大佬，你的成功吗

**Comment by web1n** [comment]
lede的luci和最新的不太一样，我已经修了你可以再试试

**Comment by COOL1000** [comment]
好的，谢谢，我试试

**Comment by web1n** [comment]
😂你是哪个学校

**Comment by COOL1000** [comment]
科大的

**Comment by COOL1000** [comment]
大佬，你编译的成功吗

**Comment by web1n** [comment]
我这里没问题，编译不能失败吧 重新拉下源码试试

**Comment by COOL1000** [comment]
好的，

**Comment by COOL1000** [comment]
谢谢大佬，成功了
