### ISSUE TITLE
校园网自动登录

### ISSUE THREAD

**Issue by Loderplay** [web1n/feed-iwifi#2]
老哥本校学生，这个联通宽带每天登陆一次属实烦，有办法实现自动登录吗，我这边有个软路由。对py啥的都不懂。

**Comment by web1n** [comment]
这个就是自动登录用的

**Comment by Loderplay** [comment]
这个直接用py运行就可以吗把账号密码改成自己的。

**Comment by Loderplay** [comment]
老哥可以编译一个IPK文件放库里吗，万分感谢了！！！

**Comment by Loderplay** [comment]
深受这个苦恼，老哥整个ipk文件真的就太感谢了。

**Comment by web1n** [comment]
可以自己编译一个
